### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by kaanaksit** [olivesgatech/CoMMonS#1]
Thank you for putting this all together. There might be a chance to use your dataset for something that I am involved in. I am little bit confused though. What is the smallest feature size of the sampled images that you are providing? Meaning what does 1 pixel corresponds to say in this image, 10 um, 100 um, 1 cm: 
![MS2_y128_x15_z50_r+60_pile_l5_ef3u_p1](https://user-images.githubusercontent.com/191201/72196228-90dcf980-33cb-11ea-95e3-9eef20c81eb7.jpg)

and why is the image saturated?

**Comment by yutinghu** [comment]
Thanks for your interest in our work and dataset. And good questions. 

Regarding Question 1: For images captured under different imaging conditions/settings, their physical image sizes vary. But I can give two examples so that you can have some ideas about the image size. An image with full resolution (2560 x 1920 pixels) and zooming level 200, the physical image size is around 1.9mm x 1.4mm; For an image with full resolution (2560 x 1920 pixels) with zooming level 50, the physical image size is around 6.6mm x 4.9mm. Therefore, you can calculate a rough number for the physical size of one pixel.

Regarding Question 2: I think the saturation are mainly caused by two reasons: 
1. Sample material property: the sample material property has an effect of reflection; 
2. Imaging system limitation: since material surface depths change dramatically under a high magnification rate, the handheld digital microscope (Dino-lite AM73915MZT), though with "extended depth of field" feature, still can not focus all texture details simultaneously. Also, the focus adjustment of the microscope has only several levels, which are not sufficient to capture different levels of depth. This saturation happens, especially for material samples with dark colors. For example, when we captured images, if we wanted to capture more details for dark regions, we would focus more on dark regions and the bright regions would be over-exposed.

Hope the above info helps.

**Comment by kaanaksit** [comment]
Thank you for your explanation. I was hoping to use this dataset to recover a 3D surface map of the samples that you tried. However, it looks like that I can estimate X-Y dimensions but not the Z one (height, depth). Is that a correct understanding or do you think there can be means to estimate that as well?

**Comment by yutinghu** [comment]
Good question. Yes, you are right. Currently, this dataset may not be appropriate for recovering 3D surface map since we don't have a ground truth dense map for the 3rd dimension (i.e. height, depth). More advanced imaging techniques/equipment capturing depth information are needed to generate such dataset and I think it might be very challenging to capture depth information for microscopic texture images with high depth resolution.

**Comment by kaanaksit** [comment]
Thank you anyways! I believe I have underestimated the finding the right dataset part of my effort. As you said, not every imaging technique is a good match for acquiring such data.
